// Generated by CoffeeScript 1.3.3
var Item, KeyHandler, List, STATE, p;

p = function(message) {
  return console.log(message);
};

STATE = {
  NORMAL: 1,
  HIDDEN: 2,
  SELECTED: 4
};

Item = (function() {

  Item.prototype.doc = null;

  Item.prototype.tab = null;

  Item.prototype.element = null;

  Item.prototype.state = null;

  function Item(doc, tab) {
    this.doc = doc;
    this.tab = tab;
    this.state = STATE.NORMAL;
    this.element = this.doc.createElement('li');
    this.element.innerHTML = this.tab.title;
    this.select(false);
    this.show(true);
  }

  Item.prototype.select = function(yesNo) {
    if (yesNo === true) {
      this.state = STATE.SELECTED;
      return this.element.setAttribute('class', 'selected');
    } else {
      this.state = STATE.NORMAL;
      return this.element.setAttribute('class', '');
    }
  };

  Item.prototype.show = function(yesNo) {
    return this.state = yesNo === true ? STATE.NORMAL : STATE.HIDDEN;
  };

  return Item;

})();

List = (function() {

  List.prototype.doc = null;

  List.prototype.element = null;

  List.prototype.items = [];

  function List(doc, element) {
    this.doc = doc;
    this.element = element;
  }

  List.prototype.addItem = function(item) {
    return this.items.push(item);
  };

  List.prototype.clear = function() {
    return this.element.innerHTML = '';
  };

  List.prototype.refresh = function() {
    var item, _i, _len, _ref, _results;
    this.clear();
    _ref = this.items;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      if (item.state === STATE.HIDDEN) {
        continue;
      }
      _results.push(this.element.appendChild(item.element));
    }
    return _results;
  };

  List.prototype.filter = function(text) {
    var flag, item, pattern, patterns, _i, _j, _len, _len1, _ref;
    patterns = text.split(/\s+/).map(function(word) {
      return new RegExp(word, 'i');
    });
    _ref = this.items;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      flag = true;
      for (_j = 0, _len1 = patterns.length; _j < _len1; _j++) {
        pattern = patterns[_j];
        if (!item.tab.title.match(pattern)) {
          flag = false;
        }
      }
      if (flag === true) {
        item.show(true);
      } else {
        item.show(false);
      }
    }
    return this.refresh();
  };

  return List;

})();

KeyHandler = (function() {

  KeyHandler.prototype.element = null;

  KeyHandler.prototype.callbacks = {
    enter: function() {},
    selectPrev: function() {},
    selectNext: function() {},
    others: function() {}
  };

  function KeyHandler(element) {
    var self,
      _this = this;
    this.element = element;
    self = this;
    this.element.addEventListener('keyup', function(event) {
      return _this._onKeyUp(event);
    });
  }

  KeyHandler.prototype._onKeyUp = function(event) {
    return this.callbacks.others(event);
  };

  KeyHandler.prototype.check = function(event) {};

  KeyHandler.prototype.onEnter = function(callback) {};

  KeyHandler.prototype.onSelectPrev = function(callback) {};

  KeyHandler.prototype.onSelectNext = function(callback) {};

  KeyHandler.prototype.onOthers = function(callback) {
    return this.callbacks.others = callback;
  };

  return KeyHandler;

})();

window.addEventListener('load', function() {
  var doc, inputElement, keyHandler, list, listElement;
  doc = window.document;
  inputElement = doc.getElementById('input');
  listElement = doc.getElementById('list');
  keyHandler = new KeyHandler(inputElement);
  list = new List(doc, listElement);
  chrome.tabs.getAllInWindow(function(tabs) {
    var item, tab, _i, _len;
    for (_i = 0, _len = tabs.length; _i < _len; _i++) {
      tab = tabs[_i];
      item = new Item(doc, tab);
      list.addItem(item);
    }
    keyHandler.onOthers(function(event) {
      return list.filter(event.target.value);
    });
    return list.refresh();
  });
  return inputElement.focus();
});
